- name: vars preference
  hosts: local
  connection: local
  vars: #5
    NAME: from play leave
  vars_files:   #3
  - course.yaml
  vars_prompt:  #4 
  - name: NAME
    prompt: What is your NAME?
    private: false  
  tasks:  
  - name: testing variables preference
   # vars:
   #   NAME: from task level  #2
    ansible.builtin.debug:
       msg: "Name----: {{ NAME }}"    #1  

# 1. args or command line
# 2. from task
# 3. files
# 4. prompt
# 5. play level
# 6. inventory