- name: conditions checks
  hosts: local
  connection: local
  vars:
   number: 5 
  
  tasks:
   - name: Check number is grater or less
     ansible.builtin.debug:
      msg: "Give number is {{ number }} is lees then 10"
     when: number < 10 